
// Objective-C API for talking to the following Go packages
//
//	gitlab.com/nebvc/vcore/vlib
//
// File is generated by gomobile bind. Do not edit.
#ifndef __VLibiOS_FRAMEWORK_H__
#define __VLibiOS_FRAMEWORK_H__

#include "Vlib.objc.h"
#include "Universe.objc.h"

#endif
